"""initial migration

Revision ID: d4782df1b631
Revises: 
Create Date: 2024-11-30 15:30:34.884016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4782df1b631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_integration_methods',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('integration_method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_method_id'], ['integration_method.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'integration_method_id')
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('integration_methods')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integration_methods', sa.TEXT(), nullable=True))

    op.drop_table('agent_integration_methods')
    op.drop_table('integration_method')
    # ### end Alembic commands ###
